# -*- coding: utf-8 -*-
"""Kalkulator Peluang Lucky

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aP1GDKpdEtic2fRGyZXQH5ALcHOCb2X
"""

!pip install streamlit pyngrok --quiet
import streamlit as st
from math import comb
import matplotlib.pyplot as plt

st.set_page_config(page_title="Kalkulator Peluang (nCr)", layout="centered")

st.title("🎲 Kalkulator Peluang (nCr) dengan Visualisasi")

# Input nilai n dan r
n = st.number_input("Masukkan nilai n (≥ 0):", min_value=0, step=1)
r = st.number_input("Masukkan nilai r (≥ 0):", min_value=0, step=1)

# Hitung dan tampilkan hasil jika tombol diklik
if st.button("Hitung Peluang"):
    if r > n:
        st.error("Nilai r tidak boleh lebih besar dari n.")
    else:
        hasil = comb(n, r)
        st.success(f"Peluang (nCr): {hasil}")

        # Visualisasi batang sederhana
        fig, ax = plt.subplots()
        ax.bar(["nCr"], [hasil], color='skyblue')
        ax.set_ylabel("Nilai nCr")
        ax.set_title("Visualisasi Peluang (nCr)")
        st.pyplot(fig)

